apiVersion: v1
kind: Service
metadata:
  name: tailscale-service
  namespace: tailscale
spec:
  selector:
    app.kubernetes.io/name: tailscale-exporter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
